# Generated by Django 2.1.1 on 2018-10-21 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SiteDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteNumber', models.IntegerField()),
                ('siteName', models.CharField(max_length=200)),
                ('timezone', models.TimeField(default='08:00')),
            ],
        ),
        migrations.CreateModel(
            name='WMO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wmoNumber', models.IntegerField()),
                ('siteNumber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.SiteDetail')),
            ],
        ),
        migrations.CreateModel(
            name='AWS',
            fields=[
                ('equipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sites.Equipment')),
                ('timeAdj', models.IntegerField()),
                ('AWSModel', models.CharField(max_length=30)),
                ('power', models.CharField(default='mains', max_length=30)),
                ('port', models.IntegerField(default=1516)),
            ],
            bases=('sites.equipment',),
        ),
        migrations.CreateModel(
            name='Comms',
            fields=[
                ('equipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sites.Equipment')),
                ('level', models.CharField(max_length=200)),
                ('netAddress', models.CharField(max_length=30, null=True)),
                ('access', models.CharField(max_length=30)),
                ('deviceModel', models.CharField(max_length=30)),
            ],
            bases=('sites.equipment',),
        ),
        migrations.CreateModel(
            name='Radar',
            fields=[
                ('equipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sites.Equipment')),
                ('IDR', models.IntegerField()),
                ('radarModel', models.CharField(max_length=30)),
            ],
            bases=('sites.equipment',),
        ),
        migrations.AddField(
            model_name='equipment',
            name='siteNumbers',
            field=models.ManyToManyField(to='sites.SiteDetail'),
        ),
        migrations.AddField(
            model_name='aviation',
            name='siteNumber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.SiteDetail'),
        ),
        migrations.AddField(
            model_name='aws',
            name='gateway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AWS_gw', to='sites.Comms'),
        ),
    ]
