# Generated by Django 2.1.1 on 2018-10-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedetail',
            name='path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
