# Generated by Django 2.1.1 on 2018-10-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_sitedetail_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aws',
            name='timeAdj',
            field=models.CharField(choices=[('true', 'yes'), ('false', 'no')], max_length=1),
        ),
    ]
