# Generated by Django 2.1.1 on 2018-10-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20181021_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aws',
            name='timeAdj',
            field=models.CharField(choices=[('true', 'yes'), ('false', 'no')], max_length=5),
        ),
    ]
