# Generated by Django 2.1.1 on 2018-10-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_auto_20181021_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='siteNumbers',
            new_name='site',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipName',
        ),
        migrations.AddField(
            model_name='comms',
            name='Name',
            field=models.CharField(default='nextG', max_length=200),
        ),
    ]
