# Generated by Django 2.1.1 on 2018-10-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_auto_20181022_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comms',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='comms',
            name='access',
        ),
        migrations.AlterField(
            model_name='comms',
            name='deviceModel',
            field=models.CharField(choices=[('Almos', 'Almos'), ('Telvent', 'Telvent')], max_length=10),
        ),
    ]
