# Generated by Django 2.1.1 on 2018-10-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_auto_20181022_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aws',
            name='AWSModel',
            field=models.CharField(choices=[('Almos', 'Almos'), ('Telvent', 'Telvent')], max_length=30),
        ),
        migrations.AlterField(
            model_name='comms',
            name='deviceModel',
            field=models.CharField(max_length=30),
        ),
    ]
