# Generated by Django 2.1.1 on 2018-10-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_auto_20181022_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radar',
            name='radarModel',
            field=models.CharField(choices=[('2502', '2502'), ('Wurrung', 'Wurrung'), ('5C', '5C'), ('6C', '6C'), ('Selex', 'Selex')], max_length=30),
        ),
    ]
