# Generated by Django 2.1.1 on 2018-10-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_auto_20181022_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comms',
            name='level',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('tertiary', 'tertiary'), ('standalone', 'standalone')], max_length=200),
        ),
    ]
