# Generated by Django 2.1.1 on 2018-10-22 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_auto_20181022_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comms',
            name='deviceModel',
        ),
        migrations.AddField(
            model_name='comms',
            name='networkDevice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commDevice', to='sites.NetworkDevice'),
        ),
    ]
