# Generated by Django 2.1.1 on 2018-10-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0010_auto_20181022_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aws',
            name='power',
            field=models.CharField(choices=[('mains', 'mains'), ('solar', 'solar')], default='mains', max_length=30),
        ),
    ]
